<definition>
	<command name="assertTextEquals">
		<case locator-key1="HEADER">
			<execute function="AssertTextEquals#assertText" value1="Liferay helps you build feature-rich, easy-to-use web applications quickly." />
		</case>
	</command>

	<command name="click">
		<case locator-key1="WHAT_WE_DO">
			<execute function="Click#clickAtAndWait" value1="What We Do" />
		</case>
		<case locator-key1="WHO_IS_USING_LIFERAY">
			<execute function="Click#clickAtAndWait" value1="Who Is Using Liferay" />
		</case>
		<case locator-key1="LIFERAY_BENEFITS">
			<execute function="Click#clickAtAndWait" value1="Liferay Benefits" />
		</case>
	</command>

	<command name="AssertElementPresent">
		<case locator-key1="CUSTOMERS_1">
			<execute function="AssertElementPresent#assertVisible" />
		</case>
		<case locator-key1="CUSTOMERS_2">
			<execute function="AssertElementPresent#assertVisible" />
		</case>
	</command>
</definition>