<definition>
	<command name="assertTextEquals">
		<case locator-key1="HEADER">
			<execute function="AssertTextEquals#assertText" value1="See how Liferay can change the way you do business." />
		</case>
		<case locator-key1="MENU_PAGE_1">
			<execute function="AssertTextEquals#assertText" value1="Open Source: A Better Way" />
		</case>
		<case locator-key1="MENU_PAGE_2">
			<execute function="AssertTextEquals#assertText" value1="Ready to Go" />
		</case>
		<case locator-key1="MENU_PAGE_3">
			<execute function="AssertTextEquals#assertText" value1="Ready to Grow" />
		</case>
		<case locator-key1="MENU_PAGE_4">
			<execute function="AssertTextEquals#assertText" value1="Approved by IT" />
		</case>
		<case locator-key1="MENU_PAGE_5">
			<execute function="AssertTextEquals#assertText" value1="Open for Business" />
		</case>
	</command>

	<command name="click">
		<case locator-key1="WHAT_WE_DO">
			<execute function="Click#clickAtAndWait" value1="What We Do" />
		</case>
		<case locator-key1="WHO_IS_USING_LIFERAY">
			<execute function="Click#clickAtAndWait" value1="Who Is Using Liferay" />
		</case>
		<case locator-key1="LIFERAY_BENEFITS">
			<execute function="Click#clickAtAndWait" value1="Liferay Benefits" />
		</case>
	</command>
</definition>