<definition>
	<command name="assertTextEquals">
		<case locator-key1="FOOTER_DEVELOP_FASTER_MESSAGE">
			<execute function="AssertTextEquals#assertText" value1="Develop Faster." />
		</case>
		<case locator-key1="FOOTER_GETTING_STARTED_MESSAGE">
			<execute function="AssertTextEquals#assertText" value1="Need Help Getting Started?" />
		</case>
		<case locator-key1="FOOTER_SOCIAL_COLLABORATION_MESSAGE">
			<execute function="AssertTextEquals#assertText" value1="Want Easy Social Collaboration?" />
		</case>
		<case locator-key1="INFO_LINK">
			<execute function="AssertTextEquals#assertText" value1="See how Liferay makes creating apps easier" />
		</case>
		<case locator-key1="LIFERAY_BENEFITS">
			<execute function="AssertTextEquals#assertText" value1="Liferay Benefits" />
		</case>
		<case locator-key1="MENU_TAGLINE">
			<execute function="AssertTextEquals#assertText" value1="Liferay helps you build feature-rich, easy-to-use web applications quickly." />
		</case>
		<case locator-key1="MENU_PAGE_1">
			<execute function="AssertTextEquals#assertText" value1="A Foundation for Apps" />
		</case>
		<case locator-key1="MENU_PAGE_2">
			<execute function="AssertTextEquals#assertText" value1="Dynamic Websites" />
		</case>
		<case locator-key1="MENU_PAGE_3">
			<execute function="AssertTextEquals#assertText" value1="Centralized Document Management" />
		</case>
		<case locator-key1="MENU_PAGE_4">
			<execute function="AssertTextEquals#assertText" value1="Intuitive Team Collaboration" />
		</case>
		<case locator-key1="MENU_PAGE_5">
			<execute function="AssertTextEquals#assertText" value1="Tools for Business" />
		</case>
		<case locator-key1="MENU_PAGE_6">
			<execute function="AssertTextEquals#assertText" value1="Desktop &amp; Mobile Access" />
		</case>
		<case locator-key1="MENU_PAGE_7">
			<execute function="AssertTextEquals#assertText" value1="Liferay Marketplace" />
		</case>
		<case locator-key1="WHAT_WE_DO">
			<execute function="AssertTextEquals#assertText" value1="What We Do" />
		</case>
		<case locator-key1="WHO_IS_USING_LIFERAY">
			<execute function="AssertTextEquals#assertText" value1="Who Is Using Liferay" />
		</case>
	</command>

	<command name="click">
		<case locator-key1="LIFERAY_BENEFITS">
			<execute function="Click#clickAtAndWait" value1="Liferay Benefits" />
		</case>
		<case locator-key1="SIGN_IN">
			<execute function="Click#clickAtAndWait" value1="Sign In" />
		</case>
		<case locator-key1="WHAT_WE_DO">
			<execute function="Click#clickAtAndWait" value1="What We Do" />
		</case>
		<case locator-key1="WHO_IS_USING_LIFERAY">
			<execute function="Click#clickAtAndWait" value1="Who Is Using Liferay" />
		</case>
		
	</command>

	<command name="AssertElementPresent">
		<case locator-key1="DEVELOP_FASTER_LINK">
			<execute function="AssertElementPresent#assertVisible" />
		</case>
		<case locator-key1="FOOTER_DEVELOP_FASTER_LOGO">
			<execute function="AssertElementPresent#assertVisible" />
		</case>
		<case locator-key1="FOOTER_GETTING_STARTED_LOGO">
			<execute function="AssertElementPresent#assertVisible" />
		</case>
		<case locator-key1="FOOTER_SOCIAL_OFFICE_LOGO">
			<execute function="AssertElementPresent#assertVisible" />
		</case>
		<case locator-key1="GET_SOCIAL_OFFICE">
			<execute function="AssertElementPresent#assertVisible" />
		</case>
		<case locator-key1="GO_TO_LIFERAY">
			<execute function="AssertElementPresent#assertVisible" />
		</case>
		<case locator-key1="NEED_HELP_GETTING_STARTED_LINK">
			<execute function="AssertElementPresent#assertVisible" />
		</case>
		<case locator-key1="TOOLS_ADD_WEB_CONTENT">
			<execute function="AssertElementPresent#assertVisible" />
		</case>
		<case locator-key1="TOOLS_EDIT_WEB_CONTENT">
			<execute function="AssertElementPresent#assertVisible" />
		</case>
		<case locator-key1="TOOLS_SELECT_WEB_CONTENT">
			<execute function="AssertElementPresent#assertVisible" />
		</case>
		<case locator-key1="TOOLS_WEB_CONTENT_TEMPLATE">
			<execute function="AssertElementPresent#assertVisible" />
		</case>
	</command>
</definition>