<definition>
	<command name="assertClick">
		<case locator-key1="BASIC_SEARCH_BUTTON">
			<execute function="AssertClick#assertValueClickAtPause" />
		</case>
		<case locator-key1="STATUS_AVAILABLE">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
		<case locator-key1="STATUS_CURRENT">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
		<case locator-key1="UPDATE_ASSOCIATIONS_BUTTON">
			<execute function="AssertClick#assertValueClickAtAndWait" />
		</case>
	</command>
	
	<command name="assertTextEquals">
		<case locator-key1="SUCCESS_MESSAGE">
			<execute function="AssertTextEquals#assertText" />
		</case>
	</command>
</definition>