<definition>
	<command name="click">
		<case locator-key1="DASHBOARD">
			<execute function="Click#textClickAtAndWait" value1="Dashboard" />
		</case>
		<case locator-key1="USER_MENU_MY_ACCOUNT">
			<execute function="Click#textClickAtAndWait" value1="My Account" />
		</case>
		<case locator-key1="USER_MENU_MY_PROFILE">
			<execute function="Click#textClickAtAndWait" value1="My Profile" />
		</case>
		<case locator-key1="USER_MENU_SIGN_OUT">
			<execute function="Click#textClickAtAndWait" value1="Sign Out" />
		</case>
		<case comparator="startsWith" locator1="//span[@data-title='">
			<execute function="Click#makeVisibleClickAt" />
		</case>
	</command>

	<command name="mouseOver">
		<case locator-key1="USER_NAME">
			<execute function="MouseOver#mouseOverClickDockbar" />
		</case>
	</command>
</definition>