<definition>
	<command name="assertElementPresent">
		<case locator-key1="EVENT_TABLE_ACTIONS">
			<execute function="AssertElementPresent#assertVisible" />
		</case>
		<case locator-key1="EVENT_TABLE_TIME">
			<execute function="AssertElementPresent#assertVisible" />
		</case>
	</command>

	<command name="assertTextEquals">
		<case locator-key1="EVENT_TABLE_TITLE">
			<execute function="AssertTextEquals#assertText" />
		</case>
		<case locator-key1="EVENT_TABLE_TYPE">
			<execute function="AssertTextEquals#assertText" />
		</case>
		<case locator-key1="SUCCESS_MESSAGE">
			<execute function="AssertTextEquals#assertText" value1="Your request completed successfully." />
		</case>
	</command>

	<command name="click">
		<case locator-key1="ADD_EVENT_BUTTON">
			<execute function="Click#clickAtAndWait" />
		</case>
		<case locator-key1="EVENT_MENULIST_DELETE">
			<execute function="Click#clickAtAndWait" />
		</case>
		<case locator-key1="EVENT_TABLE_ACTIONS">
			<execute function="Click#clickAt" />
		</case>
		<case locator-key1="VIEW_EVENTS">
			<execute function="Click#clickAtAndWait" />
		</case>
		<case locator-key1="VIEW_SUMMARY">
			<execute function="Click#clickAtAndWait" />
		</case>
	</command>

	<command name="confirm">
		<case locator-key1="CONFIRMATION">
			<execute function="Confirm#waitForConfirmation" value1="Are you sure you want to delete this?"/>
		</case>
	</command>

	<command name="isElementNotPresent">
		<case locator-key1="EVENT_TABLE_ACTIONS">
			<execute function="IsElementNotPresent#isElementNotPresent" />
		</case>
	</command>
</definition>