<definition>
	<command name="assertClick">
		<case locator-key1="ADD_ENTRY_BUTTON">
			<execute function="AssertClick#assertValueClickAtAndWait" />
		</case>
		<case comparator="startsWith" locator-key1="ENTRY_DELETE">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
		<case comparator="startsWith" locator-key1="ENTRY_TITLE">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
		<case comparator="startsWith" locator-key1="ENTRY_EDIT">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
	</command>
</definition>