<definition>
	<command name="assertClick">
		<case locator-key1="COMMENTS_ADD">
			<execute function="AssertClick#assertTextClickAt" />
		</case>
		<case locator-key1="COMMENTS_REPLY_BUTTON">
			<execute function="AssertClick#assertValueClickAt" />
		</case>
	</command>
</definition>