<definition>
	<command name="assertClick">
		<case locator-key1="FOLDER_MENULIST_EDIT">
			<execute function="AssertClick#assertTextClickAt" />
		</case>
		<case locator-key1="ACTIONS_MENULIST_DELETE">
			<execute function="AssertClick#assertTextClickAt" />
		</case>
	</command>
</definition>