<definition>
	<command name="assertClick">
		<case locator-key1="NAVIGATION_DRAFT_PAGES">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
		<case locator-key1="WIKI_PAGE_TABLE_PAGE">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
	</command>

	<command name="assertTextEquals">
		<case locator-key1="SUCCESS_MESSAGE">
			<execute function="AssertTextEquals#assertText" value1="Your request completed successfully." />
		</case>
	</command>

	<command name="click">
		<case locator-key1="ADD_PAGE_BUTTON">
			<execute function="Click#valueClickAtAndWait" value1="Add Page" />
		</case>
		<case locator-key1="WIKI_PAGE_MENULIST_DELETE">
			<execute function="Click#textClickAtAndWait" value1="Delete" />
		</case>
		<case comparator="startsWith" locator-key1="WIKI_PAGE_TABLE_ACTIONS_">
			<execute function="Click#pauseTextClickAt" value1="Actions" />
		</case>
		<case comparator="startsWith" locator-key1="WIKI_PAGE_TABLE_PAGE_">
			<execute function="Click#clickAtAndWait" />
		</case>
	</command>
</definition>