<definition>
	<command name="assertTextEquals">
		<case locator-key1="SUCCESS_MESSAGE">
			<execute function="AssertTextEquals#assertText" value1="You have successfully updated the setup." />
		</case>
	</command>

	<command name="check">
		<case locator-key1="SETUP_DISPLAY_SETTINGS_SHOW_ACTIONS_CHECKBOX">
			<execute function="Check#clickAtConfiguration" />
		</case>
		<case locator-key1="SETUP_DISPLAY_SETTINGS_SHOW_FOLDER_MENU_CHECKBOX">
			<execute function="Check#clickAtConfiguration" />
		</case>
		<case locator-key1="SETUP_DISPLAY_SETTINGS_SHOW_NAVIGATION_LINKS_CHECKBOX">
			<execute function="Check#clickAtConfiguration" />
		</case>
		<case locator-key1="SETUP_DISPLAY_SETTINGS_SHOW_SEARCH_CHECKBOX">
			<execute function="Check#clickAtConfiguration" />
		</case>
	</command>

	<command name="click">
		<case locator-key1="SAVE_BUTTON">
			<execute function="Click#valueClickAtAndWait" value1="Save" />
		</case>
	</command>

	<command name="selectFrame">
		<case locator-key1="CONFIGURATION_IFRAME">
			<execute function="SelectFrame#selectFrameWaitForScript" />
		</case>
	</command>
</definition>