<definition>
	<command name="click">
		<case locator-key1="WIKI_PAGE_MENULIST_EDIT">
			<execute function="Click#textClickAtAndWait" value1="Edit" />
		</case>
		<case locator-key1="WIKI_PAGE_MENULIST_DELETE">
			<execute function="Click#textClickAtAndWait" value1="Delete" />
		</case>
	</command>
</definition>